//
//  GreenCellViewData.swift
//  TableauxUI
//
//  Created by Ernest DeFoy on 7/21/19.
//  Copyright © 2019 Ernest DeFoy III. All rights reserved.
//

import TableauxUI

public struct GreenCellViewData: TableauDataAdapter {
	public var constantHeight: Float?
	
	public var identifier: String = MyGreenCell.reuseIdentifier
	
	let text: String = "wefiqwwefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwwefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwwefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwwefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwwefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwwefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwwefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwwefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqewefiqwefuifiuwqefiuhwqeefuifiuwqefiuhwqe"
}
